---
version: '2.4'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper-local
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_SYNC_LIMIT=2
    networks:
      - internal

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka-local
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - internal
    depends_on:
      - zookeeper
networks:
  internal:
...
