spring:
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: PLAINTEXT
    producer:
      retries: 3
    consumer:
      max-poll-records: 1
    listener:
      ack-count: 1
      log-container-config: true

demo:
  kafka:
    topic-1:
      name: topic-01
      partitions: 1
      consumer-id: demo-consumer-01
    topic-2:
      name: topic-02
      partitions: 2
      consumer-id: demo-consumer-02
