
spring:
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: PLAINTEXT
    producer:
      retries: 3
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      max-poll-records: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-count: 1
      log-container-config: true

demo:
  kafka:
    topics:
      - key: sync
        name: topic-for-sync
        partitions: 1
        consumer-id: demo-consumer-sync
      - key: async
        name: topic-for-async
        partitions: 1
        consumer-id: demo-consumer-async
      - key: request
        name: topic-for-request
        partitions: 1
        consumer-id: demo-consumer-request
      - key: reply
        name: topic-for-reply
        partitions: 1
        consumer-id: demo-consumer-reply
